version: "3.8"
services:
  publicus:
    build: .
    container_name: publicus
    env_file:
      - .env
    volumes:
      - .:/app
      # Исключаем перезапись базы данных
      - /app/bot.db
    restart: unless-stopped
