version: "3.8"
services:
  publicus:
    build: .
    container_name: publicus
    env_file:
      - .env
    volumes:
      - .:/app
      # Монтируем базу данных отдельно, чтобы она сохранялась между перезапусками
      - ./bot.db:/app/bot.db
    restart: unless-stopped
    command: bash -c "python init_db.py && python bot.py"
